(function (e) {
  if (typeof module == "object" && typeof module.exports == "object") {
    var t = e(require, exports);
    t !== undefined && (module.exports = t);
  } else
    typeof define == "function" && define.amd && define("signaling-agent/lib/telemetry/telemetryConstants", [
      "require",
      "exports"
    ], e);
}(function (e, t) {
  var n = {
    SOURCE: { NGC_SOURCE: "SkypeConcore" },
    EVENT_TYPE: { CONVERSATION_CALL_MODALITY: "skypecosi_concore_web_csa_conversation_callmodality" },
    EXTENSIONS: {
      DATA_VERSION: "DataVersion",
      DIRECTION: "Direction",
      CONNECTED_DURATION_IN_MS: "ConnectedDurationInMsecs",
      TIME_TO_RING_IN_MS: "TimeToRingInMsecs",
      CALL_TERMINATING_END: "CallTerminatingEnd",
      NETWORK_REQUESTS_PENDING: "NetworkRequestsPending",
      NETWORK_REQUESTS_COMPLETED: "NetworkRequestsCompleted",
      LOCAL_OPERATIONS_PERFORMED: "LocalOperationsPerformed",
      TROUTER_WAIT_OPERATIONS: "TrouterWaitOperations",
      CALL_START_TIME: "CallStartTime",
      CALL_END_TIME: "CallEndTime",
      IS_GROUP_CALL: "IsGroupCall",
      IS_HOSTLESS_CALL: "IsHostLessCall",
      IS_CAST_CALL: "IsCastCall",
      IS_MEETUP_CALL: "IsMeetupCall",
      IS_ON_BEHALF_OF_CALL: "IsOnBehalfOfCall",
      CALL_END_CODE: "Code",
      CALL_END_SUB_CODE: "SubCode",
      CONVERSATION_SERVICE_URL: "ConversationServiceUrl",
      MEETING_INFO: "MeetingInfo",
      RESULT_VALUE: "ResultValue",
      RESULT_DETAIL: "ResultDetail",
      RESULT_CODE: "ResultCode",
      LOCAL_OFFER_ANSWER_GENERATION_TIMESTAMPS: "LocalOfferAnswerGenerationTimestamps",
      SELF_PARTICIPANT_ROLE: "SelfParticipantRole",
      CALLER_TYPE: "Caller_Type",
      CALLEE_TYPE: "Callee_Type",
      CALL_TYPE: "Call_Type",
      TEST_CONTEXT_ID: "Test_Context_Id",
      OUTGOING_MODALITIES: "Outgoing_Modalities",
      INCOMING_MODALITIES: "Incoming_Modalities",
      VBSS_OPERATIONS: "VBSS_Operations",
      CHANGING_CORRELATION_ID_NEW_ID: "ChangingCorrelationId_NewId",
      CHANGING_CORRELATION_ID_OLD_ID: "ChangingCorrelationId_OldId"
    },
    CONTEXT_ID: {
      CORRELATIONID: "CorrelationId",
      THREADID: "ThreadId",
      TEAMS_MESSAGEID: "TeamsMessageId",
      TEAMS_MEETINGINFO: "TeamsMeetingInfo",
      ENDPOINTID: "EndpointId",
      PARTICIPANTID: "ParticipantId",
      DATA_VERSION: "DataVersion"
    },
    CALL_TERMINATING_END: {
      LOCAL: "Local",
      REMOTE: "Remote"
    },
    RESULT_VALUE: {
      SUCCESS: "Success",
      FAILURE: "Failure"
    },
    NETWORK_REQUESTS: {
      SEND_MEDIA_ANSWER: "SendMediaAnswer",
      START_RENEGOTIATION: "StartRenegotiation",
      SEND_MEDIA_ACKNOWLEDGEMENT: "SendMediaAcknowledgement",
      SEND_MEDIA_REJECTION: "SendMediaRejection",
      ADD_PARTICIPANT: "AddParticipant",
      REMOVE_PARTICIPANT: "RemoveParticipant",
      SEND_ACCEPTANCE: "SendAcceptance",
      SEND_ACCEPTANCE_ACKNOWLEDGEMENT: "SendAcceptanceAcknowledgement",
      END_CALL: "EndCall",
      CANCEL_CALL: "CancelCall",
      REJECT_CALL: "RejectCall",
      JOIN_CONVERSATION: "JoinConversation",
      JOIN_CONVERSATION_WITHOUT_CALL_MODALITY: "JoinConversationWithoutCallModality",
      LEAVE_CONVERSATION: "LeaveConversation",
      DELETE_CONVERSATION: "DeleteConversation",
      PLACE_CALL: "PlaceCall",
      UPDATE_CONVERSATION_LINKS: "UpdateConversationLinks",
      SEND_CALL_ATTACH: "SendCallAttach",
      SEND_CALL_PROGRESS: "SendCallProgress",
      SEND_KEEP_ALIVE: "SendKeepAlive",
      ADD_CONTENT_SHARING_MODALITY: "AddContentSharingModality",
      LEAVE_CONTENT_SHARING: "LeaveContentSharing",
      TAKE_CONTROL_CONTENT_SHARING: "TakeControlContentSharing",
      UPDATE_SESSION_STATE_CONTENT_SHARING: "UpdateSessionStateContentSharing",
      JOIN_CONTENT_SHARING: "JoinContentSharing",
      UPDATE_PARTICIPANT_STATE_CONTENT_SHARING: "UpdateParticipantStateContentSharing",
      MUTE: "Mute",
      UNMUTE: "Unmute",
      SEND_CONTROL_VIDEO_STREAMING: "SendControlVideoStreaming",
      APPROVE_UNMUTE: "ApproveUnmute",
      REJECT_UNMUTE: "RejectUnmute",
      SEND_TRANSFER_REQUEST: "SendTransferRequest",
      TRANSFER_ACCEPTANCE: "TransferAcceptance",
      TRANSFER_COMPLETION: "TransferCompletion"
    },
    LOCAL_OPERATIONS: {
      HANDLE_MEDIA_ACKNOWLEDGEMENT: "HandleMediaAcknowledgement",
      HANDLE_MEDIA_NEGOTIATION_FAILURE: "HandleMediaNegotiationFailure",
      HANDLE_MEDIA_ANSWER: "HandleMediaAnswer",
      HANDLE_MEDIA_OFFER: "HandleMediaOffer",
      REJECT_RENEGOTIATION: "RejectRenegotiation",
      HANDLE_RETARGET_COMPLETED: "HandleRetargetCompleted",
      HANDLE_MEDIA_ANSWER_TIMEOUT: "HandleMediaAnswerTimeout",
      HANDLE_MEDIA_ACKNOWLEDGEMENT_TIMEOUT: "HandleMediaAcknowledgementTimeout",
      ACCEPT_RENEGOTIATION: "AcceptRenegotiation",
      START_RENEGOTIATION: "StartRenegotiation",
      ADD_MODALITY_TIMEOUT: "AddModalityTimeout",
      ADD_PARTICIPANT: "AddParticipant",
      ADD_PARTICIPANT_TIMEOUT: "AddParticipantTimeout",
      REMOVE_PARTICIPANT: "RemoveParticipant",
      REMOVE_PARTICIPANT_TIMEOUT: "RemoveParticipantTimeout",
      HANDLE_ADD_PARTICIPANT_SUCCESS: "HandleAddParticipantSuccess",
      HANDLE_ADD_PARTICIPANT_FAILURE: "HandleAddParticipantFailure",
      HANDLE_ADD_PARTICIPANT_MODALITY_FAILURE: "HandleAddParticipantModalityFailure",
      HANDLE_REMOVE_PARTICIPANT_SUCCESS: "HandleRemoveParticipantSuccess",
      HANDLE_REMOVE_PARTICIPANT_FAILURE: "HandleRemoveParticipantFailure",
      HANDLE_ROSTER_UPDATE: "HandleRosterUpdate",
      HANDLE_CONVERSATION_UPDATE: "HandleConversationUpdate",
      SET_SUBJECT: "SetSubject",
      SET_THREADID: "SetThreadId",
      SET_CALLOPTIONS: "SetCallOptions",
      SET_TRANSFER_CONTEXT: "SetTransferContext",
      START_CALL: "StartCall",
      JOIN_CALL: "JoinCall",
      JOIN_CONVERSATION_WITHOUT_CALL_MODALITY: "JoinConversationWithoutCallModality",
      HANDLE_INCOMING_CALL: "HandleIncomingCall",
      END_CALL: "EndCall",
      SET_PROVISIONAL_ANSWER: "SetProvisionalAnswer",
      ACCEPT_CALL: "AcceptCall",
      HANDLE_CALL_ACCEPTANCE_ACK: "HandleCallAcceptanceAck",
      HANDLE_CALL_ACCEPTANCE: "HandleCallAcceptance",
      HANDLE_CALL_ESTABLISHMENT_TIMEOUT: "HandleCallEstablishmentTimeout",
      HANDLE_CALL_END: "HandleCallEnd",
      HANDLE_CALL_PROGRESS: "HandleCallProgress",
      TROUTER_URL_CHANGED: "TrouterUrlChanged",
      ADD_CONTENT_SHARING_MODALITY: "AddContentSharingModality",
      LEAVE_CONTENT_SHARING: "LeaveContentSharing",
      TAKE_CONTROL_CONTENT_SHARING: "TakeControlContentSharing",
      UPDATE_SESSION_STATE_CONTENT_SHARING: "UpdateSessionStateContentSharing",
      JOIN_CONTENT_SHARING: "JoinContentSharing",
      UPDATE_PARTICIPANT_STATE_CONTENT_SHARING: "UpdateParticipantStateContentSharing",
      HANDLE_CONTENT_SHARING_UPDATE: "HandleContentSharingUpdate",
      HANDLE_CONTENT_SHARING_END: "HandleContentSharingEnd",
      HANDLE_ADD_MODALITY_SUCCESS: "HandleAddModalitySuccess",
      HANDLE_ADD_MODALITY_FAILURE: "HandleAddModalityFailure",
      MUTE: "Mute",
      UNMUTE: "Unmute",
      UNMUTE_TIMEOUT: "UnmuteTimeout",
      HANDLE_UNMUTE_CONFIRM: "HandleUnmuteConfirm",
      HANDLE_UNMUTE_SUCCESS: "HandleUnmuteSuccess",
      HANDLE_UNMUTE_FAILURE: "HandleUnmuteFailure",
      APPROVE_UNMUTE: "ApproveUnmute",
      REJECT_UNMUTE: "RejectUnmute",
      HANDLE_CONTROL_VIDEO_STREAMING: "HandleControlVideoStreaming",
      HANDLE_DOMINANT_SPEAKER_INFO: "HandleDominantSpeakerInfo",
      HANDLE_CSRC_INFO: "HandleCsrcInfo",
      SEND_WEBRTC_MEDIA_NOTIFICATION: "SendWebRtcMediaNotification",
      HANDLE_BALANCE_UPDATE: "HandleBalanceUpdate",
      TRANSFER_CALL: "TransferCall",
      HANDLE_TRANSFER_ACCEPTANCE: "HandleTransferAcceptance",
      HANDLE_TRANSFER_COMPLETION: "HandleTransferCompletion",
      HANDLE_TRANSFER_REQUESTED: "HandleTransferRequested",
      HANDLE_CALL_TRANSFER_TIMEOUT: "HandleCallTransferTimeout"
    },
    DIRECTION: {
      INCOMING: "Incoming",
      OUTGOING: "Outgoing"
    },
    ROLE: {
      CALLER: "caller",
      CALLEE: "callee",
      JOIN: "join",
      JOIN_FOR_ROSTER_ONLY: "joinForRosterOnly"
    },
    VBSS_OPERATION: {
      START: "Start",
      STOP: "Stop",
      REJECTED: "Rejected",
      REMOTE_START: "RemoteStart",
      TIMEOUT: "Timeout",
      CALL_END: "CallEnd"
    },
    LOCAL_OFFER_ANSWER_OPERATIONS: {
      INITIAL_OFFER_GENERATION_STARTED: "InitialOfferGenerationStarted",
      INITIAL_OFFER_GENERATION_ENDED: "InitialOfferGenerationEnded",
      FINAL_ANSWER_PROCESSING_STARTED: "FinalAnswerProcessingStarted",
      FINAL_ANSWER_PROCESSING_ENDED: "FinalAnswerProcessingEnded",
      PROVISIONAL_ANSWER_PROCESSING_STARTED: "ProvisonalAnswerProcessingStarted",
      PROVISIONAL_ANSWER_PROCESSING_ENDED: "ProvisonalAnswerProcessingEnded",
      NEGOTIATION_COMPLETED: "NegotiationCompleted",
      INITIAL_OFFER_PROCESSING_STARTED: "InitialOfferProcessingStarted",
      INITIAL_OFFER_PROCESSING_ENDED: "InitialOfferProcessingEnded",
      FINAL_ANSWER_GENERATION_STARTED: "FinalAnswerGenerationStarted",
      FINAL_ANSWER_GENERATION_ENDED: "FinalAnswerGenerationEnded",
      PROVISIONAL_ANSWER_GENERATION_STARTED: "ProvisionalAnswerGenerationStarted",
      PROVISIONAL_ANSWER_GENERATION_ENDED: "ProvisionalAnswerGenerationEnded",
      RENEGOTIATION_OFFER_GENERATION_STARTED: "RenegotiationOfferGenerationStarted",
      RENEGOTIATION_OFFER_GENERATION_ENDED: "RenegotiationOfferGenerationEnded",
      RENEGOTIATION_ANSWER_PROCESSING_STARTED: "RenegotiationAnswerProcessingStarted",
      RENEGOTIATION_ANSWER_PROCESSING_ENDED: "RenegotiationAnswerProcessingEnded",
      RENEGOTIATION_OFFER_PROCESSING_STARTED: "RenegotiationOfferProcessingStarted",
      RENEGOTIATION_OFFER_PROCESSING_ENDED: "RenegotiationOfferProcessingEnded",
      RENEGOTIATION_ANSWER_GENERATION_STARTED: "RenegotiationAnswerGenerationStarted",
      RENEGOTIATION_ANSWER_GENERATION_ENDED: "RenegotiationAnswerGenerationEnded"
    },
    TROUTER_WAIT_OPERATION: {
      STARTED: "Started",
      ENDED: "Ended"
    }
  };
  t.__esModule = !0;
  t["default"] = n;
}));
